if [[ -f /etc/profile ]]; then
  source /etc/profile
fi

if [[ -f /etc/bash/bashrc ]]; then
  source /etc/bash/bashrc
fi

export FISHBOWL_HOME="${FISHBOWL_HOME:-/fishbowl/home}"
export HOME="${HOME:-${FISHBOWL_HOME}}"
export PATH="${HOME}/.local/bin:${PATH}"

source /fishbowl/bash_env.sh
