if [[ -f /etc/profile ]]; then
  source /etc/profile
fi

if [[ -f /etc/bash/bashrc ]]; then
  source /etc/bash/bashrc
fi

export AGENTFENCE_HOME="${AGENTFENCE_HOME:-/agentfence/home}"
export HOME="${HOME:-${AGENTFENCE_HOME}}"
export PATH="${HOME}/.local/bin:${PATH}"

source /agentfence/bash_env.sh
